## Imbalanced dataset 

In [ ]:
# !pip install imblearn

In [ ]:
from sklearn.svm import SVC
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split 
from sklearn import metrics 
from sklearn.datasets import make_classification
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import precision_recall_fscore_support, classification_report,confusion_matrix, accuracy_score
from sklearn.svm import SVC
from sklearn import datasets, metrics
from sklearn.datasets import load_iris
%matplotlib inline

from sklearn import datasets, metrics
from sklearn.datasets import load_iris
%matplotlib inline

In [ ]:
df = pd.read_csv('Cancer_dataset.csv')

In [ ]:
df.drop('Unnamed: 3', axis=1)
df.head(3)

Age                                               Race  \
0   43  Other (American Indian/AK Native, Asian/Pacifi...   
1   47  Other (American Indian/AK Native, Asian/Pacifi...   
2   67                                              White   

                   Marital Status  Unnamed: 3 T Stage  N Stage 6th Stage  \
0  Married (including common law)         NaN       T2      N3      IIIC   
1  Married (including common law)         NaN       T2      N2      IIIA   
2  Married (including common law)         NaN       T2      N1       IIB   

                                 Grade   A Stage  Tumor Size Estrogen Status  \
0  Moderately differentiated; Grade II  Regional          40        Positive   
1  Moderately differentiated; Grade II  Regional          45        Positive   
2     Poorly differentiated; Grade III  Regional          25        Positive   

  Progesterone Status  Regional Node Examined  Reginol Node Positive  \
0            Positive                      19                     11   
1            Positive                      25                      9   
2            Positive                       4                      1   

   Survival Months Status  
0                1  Alive  
1                2  Alive  
2                2   Dead

In [ ]:
df['Status'].value_counts()

Alive    3408
Dead      616
Name: Status, dtype: int64

## Label encoding for categorical data

In [ ]:
df.columns

Index(['Age', 'Race', 'Marital Status', 'Unnamed: 3', 'T Stage ', 'N Stage',
       '6th Stage', 'Grade', 'A Stage', 'Tumor Size', 'Estrogen Status',
       'Progesterone Status', 'Regional Node Examined',
       'Reginol Node Positive', 'Survival Months', 'Status'],
      dtype='object')

In [ ]:
df.dtypes

Age                         int64
Race                       object
Marital Status             object
Unnamed: 3                float64
T Stage                    object
N Stage                    object
6th Stage                  object
Grade                      object
A Stage                    object
Tumor Size                  int64
Estrogen Status            object
Progesterone Status        object
Regional Node Examined      int64
Reginol Node Positive       int64
Survival Months             int64
Status                     object
dtype: object

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

for i in df.columns:
    if(df[i].dtype==df['Age'].dtype):
        continue
    else:
        df[i] = le.fit_transform(df[i].values)

In [ ]:
df.head(3)

Age  Race  Marital Status  Unnamed: 3  T Stage   N Stage  6th Stage  Grade  \
0   43     1               1           0         1        2          4      0   
1   47     1               1           0         1        1          2      0   
2   67     2               1           0         1        0          1      1   

   A Stage  Tumor Size  Estrogen Status  Progesterone Status  \
0        1          40                1                    1   
1        1          45                1                    1   
2        1          25                1                    1   

   Regional Node Examined  Reginol Node Positive  Survival Months  Status  
0                      19                     11                1       0  
1                      25                      9                2       0  
2                       4                      1                2       1

## Train test split

In [ ]:
from sklearn.model_selection import train_test_split
y = df['Status']
df=df.drop('Status', axis=1)
X_train, X_test = train_test_split(df, test_size=0.2)
y_train, y_test = train_test_split(y, test_size=0.2)

In [ ]:
len(X_train), len(X_test)
len(y_train), len(y_test)

(3219, 805)

## SMOTE 

In [ ]:
from imblearn.over_sampling import SMOTE 
sm = SMOTE()
X_smote_train, y_smote_train = sm.fit_resample(X_train, y_train)

In [ ]:
np.unique(y_smote_train,return_counts=True)

(array([0, 1]), array([2738, 2738], dtype=int64))

In [ ]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
X_smote_train = scalar.fit_transform(X_smote_train)
X_test = scalar.fit_transform(X_test)

In [ ]:
svc = SVC() #default kernel is RBF 
clf = svc.fit(X_smote_train,y_smote_train)
y_pred = svc.predict(X_test)
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred))
print()
print("Classifiction Report :")
print(classification_report(y_test, y_pred))

Confusion Matrix: 
[[395 275]
 [ 83  52]]

Classifiction Report :
              precision    recall  f1-score   support

           0       0.83      0.59      0.69       670
           1       0.16      0.39      0.23       135

    accuracy                           0.56       805
   macro avg       0.49      0.49      0.46       805
weighted avg       0.71      0.56      0.61       805



## BorderLine SMOTE

In [ ]:
from imblearn.over_sampling import BorderlineSMOTE
oversample = BorderlineSMOTE()
X_train_border_smote, y_train_border_smote = oversample.fit_resample(X_train, y_train)

In [ ]:
np.unique(y_train_border_smote,return_counts=True)

(array([0, 1]), array([2738, 2738], dtype=int64))

In [ ]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
X_train_border_smote = scalar.fit_transform(X_train_border_smote)
X_test = scalar.fit_transform(X_test)

In [ ]:
svc = SVC() #default kernel is RBF 
clf = svc.fit(X_train_border_smote,y_train_border_smote)
y_pred = svc.predict(X_test)
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred))
print()
print("Classifiction Report :")
print(classification_report(y_test, y_pred))

Confusion Matrix: 
[[426 244]
 [ 89  46]]

Classifiction Report :
              precision    recall  f1-score   support

           0       0.83      0.64      0.72       670
           1       0.16      0.34      0.22       135

    accuracy                           0.59       805
   macro avg       0.49      0.49      0.47       805
weighted avg       0.72      0.59      0.63       805

